[package]
name = "tui_searcher"
version = "0.1.0"
edition = "2024"
description = "Tui fuzzy searcher"
license = "MIT"

[dependencies]
ratatui = "0.29.0"
frizbee = { git = "https://github.com/saghen/frizbee.git", branch = "main" }
anyhow = "1.0.100"
tui-textarea = "0.7.0"
